---

- name: Install .NET Core packages
  community.general.homebrew_cask:
    name: dotnet-sdk

- name: Configure zsh
  ansible.builtin.copy:
    src: zshrc
    dest: "{{ ansible_user_dir }}/.zshrc.d/dotnet.zsh"
    mode: '0644'
