---

- name: Install AWS CLI
  community.general.homebrew:
    name: awscli

- name: Configure zsh
  ansible.builtin.copy:
    src: zshrc
    dest: "{{ ansible_user_dir }}/.zshrc.d/awscli.zsh"
    mode: '0644'
