---

- hosts: workstations
  roles:
    - role: arch-base
      tags: ["bootstrap"]
    - role: keychron
      tags: ["keychron"]
    - role: logitech
      tags: ["logitech"]
    - role: dell
      tags: ["dell"]
    - role: git
      tags: ["git"]
    - role: zsh
      tags: ["zsh"]
    - role: tmux
      tags: ["tmux"]
    - role: neovim
      tags: ["neovim"]
    - role: kde
      tags: ["kde"]
    - role: sway
      tags: ["sway"]
    - role: sddm
      tags: ["sddm"]
    - role: browsers
      tags: ["browsers"]
    - role: slack
      tags: ["slack"]
    - role: telegram
      tags: ["telegram"]
    - role: docker
      tags: ["docker"]
    - role: jetbrains
      tags: ["jetbrains"]
    - role: node
      tags: ["node"]
    - role: dotnet
      tags: ["dotnet"]
    - role: go
      tags: ["go"]
