---

- hosts: workstations
  roles:
    - role: arch-base
      tags: ["bootstrap"]
    - role: keychron
      tags: ["keychron"]
    - role: logitech
      tags: ["logitech"]
    - role: dell
      tags: ["dell"]
    - role: lenovo
      tags: ["lenovo"]
    - role: git
      tags: ["git"]
    - role: zsh
      tags: ["zsh"]

# todo: re-enable, fails due to host key verification when doing ls-remote for some of the plugins
#    - role: tmux
#      tags: ["tmux"]

#  - role: neovim
#    tags: ["neovim"]
    - role: kde
      tags: ["kde"]
#  - role: gnome
#    tags: ["gnome"]
    - role: gdm
      tags: ["gdm"]
    - role: i3
      tags: ["i3"]
#  - role: browsers
#    tags: ["browsers"]
#  - role: libreoffice
#    tags: ["libreoffice"]
#  - role: electron
#    tags: ["electron"]
#  - role: slack
#    tags: ["slack"]
#  - role: telegram
#    tags: ["telegram"]
#  - role: signal
#    tags: ["signal"]
    - role: docker
      tags: ["docker"]
#  - role: jetbrains
#      tags: ["jetbrains"]
#    - role: node
#      tags: ["node"]
#    - role: dotnet
#      tags: ["dotnet"]
#    - role: go
#      tags: ["go"]
