---

- hosts: workstations
  roles:
      - { role: base, tags: ["base"] }
      - { role: shell, tags: ["shell"] }
      - { role: desktop, tags: ["desktop"] }
      - { role: devenv, tags: ["devenv"] }
      - { role: gcloud, tags: ["gcloud", "devenv"] }
      - { role: helm, tags: ["helm", "devenv"] }
