---

- hosts: workstations
  roles:
      - { role: ssh-keys, tags: ["base", "ssh-keys"] }
      - { role: git, tags: ["base", "git"] }
      - { role: coreutils, tags: ["base", "coreutils"] }
      - { role: python, tags: ["base", "devenv", "python"] }
      - { role: vim, tags: ["base", "devenv", "vim"] }
      - { role: zsh, tags: ["base", "zsh"] }
      - { role: tmux, tags: ["base", "tmux"] }
      - { role: macos, tags: ["desktop", "macos"] }
      - { role: fonts, tags: ["desktop", "fonts"] }
      - { role: firefox, tags: ["desktop", "firefox"] }
      - { role: chrome, tags: ["desktop", "chrome"] }
      - { role: iterm, tags: ["desktop", "iterm"] }
      - { role: dropbox, tags: ["desktop", "dropbox"] }
      - { role: onedrive, tags: ["desktop", "onedrive"] }
      - { role: office, tags: ["desktop", "office"] }
      - { role: slack, tags: ["desktop", "slack"] }
      - { role: teams, tags: ["desktop", "teams"] }
      - { role: signal, tags: ["desktop", "signal"] }
      - { role: whatsapp, tags: ["desktop", "whatsapp"] }
      - { role: vlc, tags: ["desktop", "vlc"] }
      - { role: spotify, tags: ["desktop", "spotify"] }
      - { role: docker, tags: ["devenv", "docker"] }
      - { role: vscode, tags: ["devenv", "vscode"] }
      - { role: go, tags: ["devenv", "go"] }
      - { role: dotnet, tags: ["devenv", "dotnet"] }
      - { role: node, tags: ["devenv", "node"] }
      - { role: virtualbox, tags: ["devenv", "virtualbox"] }
      - { role: vagrant, tags: ["devenv", "vagrant"] }
      - { role: terraform, tags: ["devenv", "terraform"] }
      - { role: helm, tags: ["devenv", "kubernetes", "helm"] }
      - { role: stern, tags: ["devenv", "kubernetes", "stern"] }
      - { role: istio, tags: ["devenv", "kubernetes", "istio"] }
      - { role: minikube, tags: ["devenv", "kubernetes", "minikube"] }
      - { role: gcloud, tags: ["devenv", "gcloud"] }
      - { role: hugo, tags: ["devenv", "hugo"] }
      - { role: pgo, tags: ["devenv", "kubernetes", "pgo"] }
