---

- name: Install bspwm and dependencies
  become: true
  pacman: name={{ item }} state=present
  with_items:
    - bspwm
    - feh

- name: Prepare bspwm configuration directories
  file: path=~/.config/bspwm state=directory

- name: Install bspwm configuration
  copy: src=bspwm/{{ item }} dest=~/.config/bspwm/{{ item }} mode=0755
  with_items:
    - bspwmrc
    - configure_monitors
