---

- name: Include desktop dependencies
  become: true
  pacman: name={{ item }} state=present
  with_items:
    - xorg-xrandr
    - xorg-xrdb
    - xorg-xsetroot
    - network-manager-applet

- include: fonts.yml
- include: sddm.yml
- include: termite.yml
- include: kde.yml
- include: kdeconnect.yml
- include: latte-dock.yml
- include: firefox.yml
- include: slack.yml
- include: vlc.yml
- include: networkmanager.yml
