---

- name: Install sddm
  become: true
  pacman: name=sddm state=present

- name: Prepare sddm configuration directories
  become: true
  file: path=/etc/sddm.conf.d state=directory

- name: Configure sddm
  become: true
  copy: src=sddm/hide-users.conf dest=/etc/sddm.conf.d/uid.conf

- name: Enable sddm
  become: true
  systemd: name=sddm enabled=yes
