---

- name: Create wallpaper directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/Pictures/Wallpapers"
    state: directory

- name: Install wallpapers
  ansible.builtin.copy:
    src: .
    dest: "{{ ansible_user_dir }}/Pictures/Wallpapers/"
    mode: '0644'
