---

- name: Install Yabai packages
  community.general.homebrew:
    name:
      - koekeishiya/formulae/yabai
      - koekeishiya/formulae/skhd

- name: Configure passwordless sudo for loading scripting additions
  ansible.builtin.copy:
    src: sudoers
    dest: "/private/etc/sudoers.d/yabai"
    mode: '0644'
  become: true

- name: Prepare yabai configuration directories
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/{{ item }}"
    state: directory
  with_items:
    - yabai
    - skhd
