---

- name: Install Visual Studio Code packages
  become: true
  pacman: name={{ item }} state=present
  with_items:
    - code

- name: Install Visual Studio Code extensions
  shell: code --install-extension {{ item }}
  with_items:
    - ms-kubernetes-tools.vscode-kubernetes-tools
    - ms-python.python
    - msjsdiag.debugger-for-chrome
    - PeterJausovec.vscode-docker
    - ms-vscode.Go
    - vscodevim.vim
    - vscoss.vscode-ansible
    - ms-vscode.csharp

- name: Create Visual Studio Code config directories
  file: path="~/.config/Code - OSS/User" state=directory

- name: Configure Visual Studio Code
  template: src="settings.json.j2" dest="~/.config/Code - OSS/User/settings.json" mode=0644
