---

- name: Install Visual Studio Code
  homebrew_cask:
    name: visual-studio-code
    state: present

- name: Install Visual Studio Code extensions
  shell: code --install-extension {{ item }} --force
  with_items:
    - ms-kubernetes-tools.vscode-kubernetes-tools
    - ms-python.python
    - msjsdiag.debugger-for-chrome
    - PeterJausovec.vscode-docker
    - ms-vscode.Go
    - vscodevim.vim
    - mauve.terraform
    - zxh404.vscode-proto3
    - redhat.vscode-yaml
    - heptio.jsonnet
    - aeschli.vscode-css-formatter
    - azemoh.one-monokai
    - mishkinf.goto-next-previous-member
    - rebornix.ruby
    - castwide.solargraph
    - kumar-harsh.graphql-for-vscode
    - vscode-icons-team.vscode-icons
    - zhuangtongfa.material-theme
    - editorconfig.editorconfig

- name: Create Visual Studio Code config directories
  file:
    path: "{{item}}"
    state: directory
  with_items:
    - "~/Library/Application Support/Code/User"
    - "~/Library/Application Support/Code/User/snippets"

- name: Configure Visual Studio Code
  template:
    src: "{{item}}.j2"
    dest: "~/Library/Application Support/Code/User/{{item}}"
    mode: 0644
  with_items:
    - "settings.json"
    - "keybindings.json"

- name: Configure Visual Studio Code snippets
  template:
    src: "{{item}}-snippets.json.j2"
    dest: "~/Library/Application Support/Code/User/snippets/{{item}}.json"
    mode: 0644
  with_items:
    - "go"
