---

- name: Install Visual Studio Code
  homebrew_cask:
    name: visual-studio-code
    state: present

- name: Install Visual Studio Code extensions
  shell: code --install-extension {{ item }} --force
  with_items:
    - ms-kubernetes-tools.vscode-kubernetes-tools
    - ms-python.python
    - msjsdiag.debugger-for-chrome
    - PeterJausovec.vscode-docker
    - ms-vscode.Go
    - vscodevim.vim
    - vscoss.vscode-ansible
    - ms-vscode.csharp
    - formulahendry.dotnet-test-explorer
    - mauve.terraform
    - zxh404.vscode-proto3
    - redhat.vscode-yaml
    - heptio.jsonnet
- name: Create Visual Studio Code config directories
  file: path="~/Library/Application Support/Code/User" state=directory

- name: Configure Visual Studio Code
  template:
    src: "{{item}}.j2"
    dest: "~/Library/Application Support/Code/User/{{item}}"
    mode: 0644
  with_items:
    - "settings.json"
    - "keybindings.json"
