---

- name: Create the installation directory
  become: true
  file:
    path: "{{operator_sdk_install_path}}"
    state: directory

- name: Install Operator SDK
  become: true
  get_url:
    url: "{{operator_sdk_download_url}}"
    dest: "{{operator_sdk_install_path}}/operator-sdk"
    mode: 0755

- name: Configure shell
  template: src="zshrc.j2" dest="~/.zshrc.d/operator-sdk.zsh" mode=0644
