---

- name: Install Compton
  become: true
  pacman: name=compton state=present

- name: Prepare Compton configuration directories
  file: path=~/.config/compton state=directory

- name: Install Compton configuration
  copy: src=compton.conf dest=~/.config/compton/compton.conf
