require('user.options')
require('user.keymaps')
require('user.plugins')
require('user.colorscheme')

-- plugin configs
require('user.bufferline')
require('user.comment')
require('user.gitsigns')
require('user.indent-blankline')
require('user.lsp')
require('user.lualine')
require('user.luasnip')
require('user.neo-tree')
require('user.nvim-autopairs')
require('user.nvim-cmp')
require('user.nvim-treesitter')
require('user.symbols-outline')
require('user.telescope')
require('user.treesitter-context')
require('user.trouble')
require('user.vim-test')
require('user.which-key')
