---

- name: Prepare Neovim configuration directories
  file: path=~/{{ item }} state=directory
  with_items:
    - .vim/bundle
    - .vim/tmp/undo
    - .vim/tmp/backup
    - .vim/tmp/swap
    - .config/nvim

- name: Install Vundle
  git: repo=https://github.com/VundleVim/Vundle.vim dest=~/.vim/bundle/Vundle.vim accept_hostkey=yes
