# Configuration for Alacritty, the GPU enhanced terminal emulator.

# Import additional configuration files
#
# Imports are loaded in order, skipping all missing files, with the importing
# file being loaded last. If a field is already present in a previous import, it
# will be replaced.
#
# All imports must either be absolute paths starting with `/`, or paths relative
# to the user's home directory starting with `~/`.
#import:
#  - /path/to/alacritty.yml

# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty itself.
env:
  TERM: xterm-256color

window:
  # Window padding (changes require restart)
  #
  # Blank space added around the window in pixels. This padding is scaled
  # by DPI and the specified value is always added at both opposing sides.
  padding:
    x: 5
    y: 5

  # Background opacity
  #
  # Window opacity as a floating point number from `0.0` to `1.0`.
  # The value `0.0` is completely transparent and `1.0` is opaque.
  opacity: 0.9

# Font configuration
font:
  # Normal (roman) font face
  normal:
    family: NotoSansMono Nerd Font
    style: Regular

  # Bold font face
  bold:
    family: NotoSansMono Nerd Font
    style: Bold

  # Italic font face
  italic:
    family: NotoSansMono Nerd Font
    style: Italic

  # Bold italic font face
  bold_italic:
    family: NotoSansMono Nerd Font
    style: Bold Italic

  # Point size
  size: 9.0

# Nightfox Alacritty Colors
# Style: nightfox
# Upstream: https://github.com/edeneast/nightfox.nvim/raw/main/extra/nightfox/nightfox_alacritty.yml
colors:
  # Default colors
  primary:
    background: '0x192330'
    foreground: '0xcdcecf'
  # Normal colors
  normal:
    black:   '0x393b44'
    red:     '0xc94f6d'
    green:   '0x81b29a'
    yellow:  '0xdbc074'
    blue:    '0x719cd6'
    magenta: '0x9d79d6'
    cyan:    '0x63cdcf'
    white:   '0xdfdfe0'
  # Bright colors
  bright:
    black:   '0x575860'
    red:     '0xd16983'
    green:   '0x8ebaa4'
    yellow:  '0xe0c989'
    blue:    '0x86abdc'
    magenta: '0xbaa1e2'
    cyan:    '0x7ad4d6'
    white:   '0xe4e4e5'
  indexed_colors:
    - { index: 16, color: '0xf4a261' }
    - { index: 17, color: '0xd67ad2' }
