---

- name: Install SDDM
  community.general.pacman:
    name:
      - sddm
  become: true
  tags: [sddm]

- name: Disable the SDDM service
  ansible.builtin.service:
    name: sddm
    enabled: false
  become: true
  tags: [sddm]
