---

- name: Prepare terminfo directories
  file: path=~/.terminfo state=directory

- name: Compile terminfo files
  shell: tic -o ~/.terminfo roles/macos/files/{{ item }}.terminfo
  with_items:
    - "tmux"
    - "tmux-256color"
    - "tmux-256color-italic"
