---

- name: Install zsh
  community.general.pacman:
    name:
      - zsh
      - zsh-completions
      - bc
  become: true

- name: Create zsh configuration directories
  ansible.builtin.file:
    path: /home/trond/{{ item }}
    owner: trond
    group: trond
    mode: '0755'
    state: directory
  with_items:
    - .zsh
    - .zshrc.d

- name: Create zsh configuration files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "/home/trond/{{ item.dest }}"
    owner: trond
    group: trond
    mode: '0644'
  with_items:
    - { src: "zshrc", dest: ".zshrc" }
    - { src: "aliases", dest: ".zsh/aliases" }
    - { src: "completions", dest: ".zsh/completions" }
    - { src: "exports", dest: ".zsh/exports" }

- name: Install colortest script
  ansible.builtin.copy:
    src: colortest
    dest: /home/trond/.local/bin/colortest
    owner: trond
    group: trond
    mode: '0755'
