---

- name: Install zsh
  community.general.homebrew:
    name:
      - zsh
      - zsh-completions
      - bc

- name: Create zsh configuration directories
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/{{ item }}"
    mode: '0755'
    state: directory
  with_items:
    - .zsh
    - .zshrc.d

- name: Create zsh configuration files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ ansible_user_dir }}/{{ item.dest }}"
    mode: '0644'
  with_items:
    - { src: "zshrc", dest: ".zshrc" }
    - { src: "aliases", dest: ".zsh/aliases" }
    - { src: "completions", dest: ".zsh/completions" }
    - { src: "exports", dest: ".zsh/exports" }

- name: Install colortest script
  ansible.builtin.copy:
    src: colortest
    dest: "{{ ansible_user_dir }}/.local/bin/colortest"
    mode: '0755'
