---

- name: Install zsh
  pacman: name={{ item }} state=present
  with_items:
    - zsh
    - zsh-completions
  become: true

- name: Change shell to zsh
  user:
    name: "{{ ansible_user }}"
    shell: /bin/zsh
  become: true

- name: Install zsh configuration
  copy: src={{ item.src }} dest=~/{{item.dest }}
  with_items:
    - { src: "zshrc", dest: ".zshrc" }
    - { src: "aliases", dest: ".zsh/aliases" }
    - { src: "colors", dest: ".zsh/colors" }
    - { src: "completions", dest: ".zsh/completions" }
    - { src: "exports", dest: ".zsh/exports" }

