---

- name: Install zsh
  ansible.builtin.apt:
    name:
      - zsh
      - bc
    state: present
  become: true

- name: Create zsh configuration directories
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/{{ item }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0755'
    state: directory
  with_items:
    - .zsh
    - .zshrc.d

- name: Create zsh configuration files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ ansible_user_dir }}/{{ item.dest }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0644'
  with_items:
    - { src: "zshrc", dest: ".zshrc" }
    - { src: "aliases", dest: ".zsh/aliases" }
    - { src: "completions", dest: ".zsh/completions" }
    - { src: "exports", dest: ".zsh/exports" }

- name: Install colortest script
  ansible.builtin.copy:
    src: colortest
    dest: "{{ ansible_user_dir }}/.local/bin/colortest"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0755'

- name: Make zsh default shell
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: "/usr/bin/zsh"
  become: true
