---

- name: Install zsh
  pacman: name={{ item }} state=present
  with_items:
    - zsh
    - zsh-completions
  become: true

- name: Change shell to zsh
  user:
    name: "{{ ansible_user }}"
    shell: /bin/zsh
  become: true

- name: Install zsh configuration
  copy: src=zshrc dest=~/.zshrc

