---

istio_version: "1.0.6"
istio_download_url: "https://github.com/istio/istio/releases/download/{{istio_version}}/istio-{{istio_version}}-osx.tar.gz"
istio_install_path: "/opt/istio/{{istio_version}}"
