---

- name: Install Sway
  community.general.pacman:
    name:
      - sway
      - xdg-desktop-portal-wlr
      - swaylock
      - swayidle
      - alacritty
      - wofi
      - waybar
      - dunst
      - brightnessctl
      - gammastep
      - gnome-keyring
      - wl-clipboard
      - kanshi
      - grim
      - slurp
      - imv
      - xorg-xwayland
  become: true

- name: Install required fonts and icons
  community.general.pacman:
    name:
      - otf-font-awesome
      - noto-fonts
      - ttf-fira-code
      - nerd-fonts-complete
      - gnome-icon-theme
    executable: yay

- name: Create configuration directories
  ansible.builtin.file:
    path: "/home/trond/.config/{{ item }}"
    owner: trond
    group: trond
    mode: '0755'
    state: directory
  with_items:
    - sway
    - kitty
    - waybar

- include_tasks: config.yml

- name: Auto-start sway on tty1 login
  ansible.builtin.copy:
    src: zshrc
    dest: /home/trond/.zshrc.d/sway.zsh
    mode: '0644'

- name: Enable gnome keyring in PAM
  ansible.builtin.copy:
    src: pam-login
    dest: /etc/pam.d/login
    owner: root
    group: root
    mode: '0644'
  become: true
