---

- name: Install Gnome
  community.general.pacman:
    name:
      - gdm
      - gnome
      - gnome-shell-extension-blur-my-shell
      - gnome-shell-extension-clipboard-history
      - gnome-shell-extension-just-perfection-desktop
      - gnome-shell-extension-nightthemeswitcher
      - gnome-shell-extension-pop-shell-git
      - gnome-software-packagekit-plugin
      - gnome-themes-extra
      - gnome-tweaks
      - xdg-desktop-portal-gnome
    executable: yay

- name: Enable GDM
  ansible.builtin.service:
    name: gdm
    enabled: true
  become: true
