---

- name: Install GNOME
  community.general.pacman:
    name:
      - dconf-editor
      - gnome
      - gnome-shell-extensions
      - gnome-tweaks
      - xdg-desktop-portal-gnome
  become: true
  tags: [gnome]

- name: Install GNOME (AUR)
  community.general.pacman:
    name:
      - nerd-fonts-complete
    executable: yay

- name: Disable GDM
  ansible.builtin.service:
    name: gdm
    enabled: false
  become: true
  tags: [gnome]

- include: settings.yml
