---

- name: Install GNOME
  community.general.pacman:
    name:
      - gnome
      - gnome-tweaks
      - xdg-desktop-portal-gnome
  become: true
  tags: [gnome]

- name: Enable GDM
  ansible.builtin.service:
    name: gdm
    enabled: true
  become: true
  tags: [gnome]
