---

- name: Install Git packages
  community.general.homebrew:
    name:
      - git
      - git-lfs
      - gh

- name: Create Git configuration
  ansible.builtin.copy:
    src: gitconfig
    dest: "{{ ansible_user_dir }}/.gitconfig"
    mode: '0644'
