---

- name: Create the installation directory
  become: true
  file:
    path: "{{go_delve_install_path}}"
    owner: "{{ansible_user}}"
    state: directory

- name: Download the Delve source code
  unarchive:
    src: "{{go_delve_download_url}}"
    dest: "{{go_delve_install_path}}"
    remote_src: yes
    extra_opts:
      --strip-components=1
    creates: "{{go_delve_install_path}}/README.md"
  register: go_delve_downloaded

- name: Install Delve dependencies
  command: glide install
  args:
    chdir: "{{go_delve_install_path}}"
  environment:
    GOPATH: "{{go_delve_gopath}}"
    PATH: "{{go_install_path}}/bin:{{go_glide_install_path}}:{{ ansible_env.PATH }}"
  when: go_delve_downloaded.changed

- name: Install dlv
  shell: make install && mv "{{go_delve_gopath}}/bin/dlv" "{{go_path}}/bin/dlv"
  args:
    chdir: "{{go_delve_install_path}}"
  environment:
    GOPATH: "{{go_delve_gopath}}"
    PATH: "{{go_install_path}}/bin:{{go_glide_install_path}}:{{ ansible_env.PATH }}"
    CPATH: "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include"
  when: go_delve_downloaded.changed
