---

- name: Create the installation directory
  become: true
  file:
    path: "{{go_install_path}}"
    owner: "{{ansible_user}}"
    state: directory

- name: Download Go
  unarchive:
    src: "{{go_download_url}}"
    dest: "{{go_install_path}}"
    remote_src: yes
    extra_opts:
      --strip-components=1
    creates: "{{go_install_path}}/README.md"

- name: Configure shell
  template: src="zshrc.j2" dest="~/.zshrc.d/go.zsh" mode=0644

- name: Prepare the GOPATH
  file:
    path: "{{item}}"
    state: directory
  with_items:
    - "{{go_path}}"
    - "{{go_path}}/bin"
    - "{{go_path}}/src"
