---

- name: Create the installation directory
  become: true
  file:
    path: "{{go_gopls_install_path}}"
    owner: "{{ansible_user}}"
    state: directory

- name: Download the gopls source code
  unarchive:
    src: "{{go_gopls_download_url}}"
    dest: "{{go_gopls_install_path}}"
    remote_src: yes
    extra_opts:
      --strip-components=1
    creates: "{{go_gopls_install_path}}/README.md"
  register: go_gopls_downloaded

- name: Install gopls
  shell: go build -o gopls main.go && mv gopls "{{go_path}}/bin/gopls"
  args:
    chdir: "{{go_gopls_install_path}}/cmd/gopls"
  when: go_gopls_downloaded.changed
