---

- name: Install Go
  community.general.homebrew:
    name: go

- name: Prepare GOPATH
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.local/share/go/{{ item }}"
    state: directory
    recurse: true
  with_items:
    - bin
    - src

- name: Configure zsh
  ansible.builtin.copy:
    src: zshrc
    dest: "{{ ansible_user_dir }}/.zshrc.d/go.zsh"
    mode: '0644'
