---

- name: Install Google Cloud SDK
  homebrew_cask:
    name: google-cloud-sdk
    state: present

- name: Install Google Cloud SDK components
  shell: /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin/gcloud components install {{item}}
  with_items:
    - kubectl

- name: Configure shell
  template: src="zshrc.j2" dest="~/.zshrc.d/google-cloud-sdk.zsh" mode=0644
