---

go_path: "/Users/trond/Code/go"
go_delve_version: "1.1.0"
go_delve_download_url: "https://github.com/go-delve/delve/archive/v{{go_delve_version}}.tar.gz"
go_delve_gopath: "/opt/delve/{{go_delve_version}}"
go_delve_install_path: "{{go_delve_gopath}}/src/github.com/derekparker/delve"
