---

go_path: "/Users/trond/Code/go"
go_delve_version: "1.1.0"
go_delve_download_url: "https://github.com/go-delve/delve/archive/v{{go_delve_version}}.tar.gz"
go_delve_gopath: "/opt/delve/{{go_delve_version}}"
go_delve_install_path: "{{go_delve_gopath}}/src/github.com/derekparker/delve"
go_gopls_version: "c8dd0e73d4ac1aa8188516d9fc2bede46a8493de" # master as of 2019-04-08
go_gopls_download_url: "https://github.com/saibing/tools/tarball/{{go_gopls_version}}"
go_gopls_install_path: "/opt/gopls/{{go_gopls_version}}"
