---

- name: Install tmux
  ansible.builtin.apt:
    name: tmux
    state: present
  become: true

- name: Prepare tmux config directories
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/{{ item }}"
    state: directory
  with_items:
    - tmux
    - tmux/plugins

- name: Install tmux plugin manager
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ ansible_user_dir }}/.config/tmux/plugins/tpm"
    update: no
    accept_hostkey: yes

- name: Install tmux configuration
  ansible.builtin.copy:
    src: tmux.conf
    dest: "{{ ansible_user_dir }}/.config/tmux/tmux.conf"

- name: Configure zsh
  ansible.builtin.copy:
    src: zshrc
    dest: "{{ ansible_user_dir }}/.zshrc.d/tmux.zsh"
    mode: '0644'
