---

- name: Install tmux
  homebrew:
    name: tmux
    state: present

- name: Prepare tmux plugin manager directories
  file:
    path: ~/.tmux/plugins
    state: directory

- name: Install tmux plugin manager
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm

- name: Install tmux configuration
  copy: src=tmux.conf dest=~/.tmux.conf

- name: Configure shell
  template: src="zshrc.j2" dest="~/.zshrc.d/tmux.zsh" mode=0644
