---

- name: Install required packages
  community.general.pacman:
    name:
      - v4l-utils
      - vlc
      - zvbi
  become: true

- name: Create script to configure the camera
  ansible.builtin.copy:
    src: logitech-brio-configure.sh
    dest: /usr/local/bin/logitech-brio-configure
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Install udev rule
  ansible.builtin.copy:
    src: brio_udev
    dest: /etc/udev/rules.d/80-logitech-brio.rules
    owner: root
    group: root
    mode: '0644'
  become: true
