---

- name: Install node.js
  homebrew:
    name: node
    state: present

- name: Install typescript
  homebrew:
    name: typescript
    state: present

- name: Install yarn
  homebrew:
    name: yarn
    state: present
