---

- name: Install Node Version Manager
  community.general.homebrew:
    name: nvm

- name: Create NVM home directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.nvm"
    state: directory

- name: Configure zsh
  ansible.builtin.copy:
    src: zshrc
    dest: "{{ ansible_user_dir }}/.zshrc.d/nvm.zsh"
    mode: '0644'
