---

- name: Install Node packages
  ansible.builtin.apt:
    name:
      - nodejs
      - npm
      - yarn
    state: present
  become: true

- name: Install NVM
  ansible.builtin.git:
    repo: "git@github.com:nvm-sh/nvm.git"
    dest: "{{ ansible_user_dir }}/.nvm"
    version: "v{{ nvm_version }}"
    accept_hostkey: yes

- name: Configure shell
  ansible.builtin.copy:
    src: zshrc
    dest: "{{ ansible_user_dir }}/.zshrc.d/nvm.zsh"
    mode: '0644'
