---

- name: Install required packages
  community.general.pacman:
    name:
      - ddcutil
  become: true

- name: Load kernel modules on boot
  ansible.builtin.copy:
    src: module-load.conf
    dest: /etc/modules-load.d/i2c-dev.conf
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Create script to swap KVM inputs
  ansible.builtin.copy:
    src: dell-monitor-kvm-swap-pc.sh
    dest: /usr/local/bin/dell-monitor-kvm-swap-pc
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Allow passwordless swap of KVM inputs
  ansible.builtin.copy:
    src: trond-kvm-swap-sudo
    dest: /etc/sudoers.d/trond-kvm-swap
    owner: root
    group: root
    mode: '0440'
  become: true

- name: Create script to configure docked audio behavior
  ansible.builtin.copy:
    src: "{{ item }}.sh"
    dest: "/usr/local/bin/{{ item }}"
    owner: root
    group: root
    mode: '0755'
  with_items:
    - configure-audio-docked
    - configure-audio-undocked
  become: true
