if [ -z $DISPLAY ] && [ "$(tty)" = "/dev/tty1" ]; then
  eval $(gnome-keyring-daemon --start)
  export SSH_AUTH_SOCK
  export MOZ_ENABLE_WAYLAND=1
  export XDG_CURRENT_DESKTOP=sway
  export _JAVA_AWT_WM_NONREPARENTING=1
  exec sway
fi
