---

- name: Create the installation directory
  become: true
  file:
    path: "{{kubedb_install_path}}"
    state: directory

- name: Install KubeDB CLI
  become: true
  get_url:
    url: "{{kubedb_download_url}}"
    dest: "{{kubedb_install_path}}/kubedb"
    mode: 0755

- name: Configure shell
  template: src="zshrc.j2" dest="~/.zshrc.d/pgo.zsh" mode=0644
