---

- name: Install Sway
  community.general.pacman:
    name:
      - sway
      - xdg-desktop-portal-wlr
      - swaylock
      - swayidle
      - alacritty
      - wofi
      - waybar
      - dunst
      - brightnessctl
      - gammastep
      - gnome-keyring
      - wl-clipboard
      - kanshi
      - grim
      - slurp
      - xorg-xwayland
  become: true

- name: Install required fonts and icons
  community.general.pacman:
    name:
      - otf-font-awesome
      - noto-fonts
      - ttf-fira-code
      - nerd-fonts-complete
      - gnome-icon-theme
    executable: yay

- name: Create configuration directories
  ansible.builtin.file:
    path: "/home/trond/.config/{{ item }}"
    owner: trond
    group: trond
    mode: '0755'
    state: directory
  with_items:
    - sway
    - alacritty
    - waybar

- name: Auto-start sway on tty1 login
  ansible.builtin.copy:
    src: zshrc
    dest: /home/trond/.zshrc.d/sway.zsh
    mode: '0644'

- name: Enable gnome keyring in PAM
  ansible.builtin.copy:
    src: pam-login
    dest: /etc/pam.d/login
    owner: root
    group: root
    mode: '0644'
  become: true

#- name: Auto-start sway on tty1 login
#  ansible.builtin.copy:
#    src: zshrc
#    dest: /home/trond/.zshrc.d/sway.zsh
#    mode: '0644'

# TODO:
#  + wofi
#  - dmenu
#  - dunst?
#  - dunst noification icons, where do they come from
#  - wallpapers
#  - gammastep
#  - kanshi
#
# OTHER:
#  - redshift
#  - scripts for brightness and volume
#
# INSPIRATION
#  - https://github.com/verttj/SwayyHome/blob/master/11:11/config/sway/config (https://www.reddit.com/r/unixporn/comments/q56l1k/sway_1111/)

#- name: Install configuration files
#  ansible.builtin.copy:
#    src: "{{ item.src }}"
#    dest: "/home/trond/.config/{{ item.dest }}"
#    owner: trond
#    group: trond
#    mode: '0644'
#  with_items:
#    - { src: sway_config, dest: sway/config }
#    - { src: alacritty.yml, dest: alacritty/alacritty.yml }
#    - { src: waybar_config, dest: waybar/config }
#    - { src: waybar.css, dest: waybar/style.css }
