---

- name: Install audio packages
  community.general.pacman:
    name:
      - libpulse
      - pavucontrol
      - pipewire
      - pipewire-alsa
      - pipewire-pulse
      - pipewire-jack
      - sof-firmware
  become: true
