---

- name: Install audio packages
  community.general.pacman:
    name:
      - libpulse
      - pavucontrol
      - pipewire
      - pipewire-alsa
      - pipewire-pulse
      - pipewire-jack
      - sof-firmware
#      - pulseaudio-alsa
#      - alsa-firmware
#      - alsa-utils
#      - alsa-ucm-conf
  become: true
