---

- name: Install yay AUR helper
  ansible.builtin.shell:
    cmd: |
      git clone https://aur.archlinux.org/yay-bin.git /tmp/yay-bin
      cd /tmp/yay-bin
      makepkg -si --noconfirm > /tmp/makepkg.log
      rm -rf /tmp/yay-bin
    creates: /usr/bin/yay
  vars:
    ansible_remote_tmp: /tmp
  register: yay_installed
  become: true
  become_user: trond # become and become_user required since this runs as root for the first time during bootstrap.

- name: Generate yay AUR helper database
  ansible.builtin.shell: yay -Y --gendb
  become: true
  when: yay_installed.changed


