---

- name: Create locale.gen
  ansible.builtin.copy:
    src: locale.gen
    dest: /etc/locale.gen
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: locale-gen

- name: Generate locale.conf
  ansible.builtin.copy:
    src: locale.conf
    dest: /etc/locale.conf
    owner: root
    group: root
    mode: '0644'
  become: true
