---

- name: Create user group
  ansible.builtin.group:
    name: trond
    gid: 1000
  become: true

- name: Create user
  ansible.builtin.user:
    name: trond
    uid: 1000
    comment: Trond Nordheim
    shell: /bin/zsh
    group: trond
    groups: [wheel]
  become: true

- name: Allow sudo for created user
  ansible.builtin.copy:
    src: trond-sudo
    dest: /etc/sudoers.d/trond
    owner: root
    group: root
    mode: '0440'
  become: true

- name: Allow passwordless pacman for created user
  ansible.builtin.copy:
    src: trond-pacman-sudo
    dest: /etc/sudoers.d/trond-pacman
    owner: root
    group: root
    mode: '0440'
  become: true

- name: Create local bin directory
  ansible.builtin.file:
    path: /home/trond/.local/bin
    recurse: true
    owner: trond
    group: trond
    mode: '0755'
    state: directory

- name: Prepare SSH key directory
  ansible.builtin.file:
    path: /home/trond/.ssh
    owner: trond
    group: trond
    mode: '0750'
    state: directory

- name: Install SSH public key
  ansible.builtin.copy:
    dest: /home/trond/.ssh/id_rsa.pub
    content: "{{ ssh.public_key }}"
    owner: trond
    group: trond
    mode: '0640'

- name: Install SSH private key
  ansible.builtin.copy:
    dest: /home/trond/.ssh/id_rsa
    content: "{{ ssh.private_key }}"
    owner: trond
    group: trond
    mode: '0600'

