---

- name: Set terminal font
  shell: /usr/libexec/PlistBuddy -c "Set 'New Bookmarks':0:'{{item}}' HackNerdFontComplete-Regular 12" ~/Library/Preferences/com.googlecode.iterm2.plist
  with_items:
    - "Normal Font"
    - "Non Ascii Font"

- name: Set transparency
  shell: /usr/libexec/PlistBuddy -c "Set 'New Bookmarks':0:'Transparency' 0.015" ~/Library/Preferences/com.googlecode.iterm2.plist
