---

- name: Download color scheme
  get_url:
    url: https://raw.githubusercontent.com/rakr/iterm-two-firewatch/master/two-firewatch-dark.itermcolors
    dest: /tmp/two-firewatch-dark.itermcolors

- name: Install color scheme
  shell: open /tmp/two-firewatch-dark.itermcolors

- name: Set terminal font
  shell: /usr/libexec/PlistBuddy -c "Set 'New Bookmarks':0:'{{item}}' HackNerdFontComplete-Regular 12" ~/Library/Preferences/com.googlecode.iterm2.plist
  with_items:
    - "Normal Font"
    - "Non Ascii Font"

- name: Set transparency
  shell: /usr/libexec/PlistBuddy -c "Set 'New Bookmarks':0:'Transparency' 0.015" ~/Library/Preferences/com.googlecode.iterm2.plist

- name: Set terminal type
  shell: /usr/libexec/PlistBuddy -c "Set 'New Bookmarks':0:'Terminal Type' xterm-256color-italic" ~/Library/Preferences/com.googlecode.iterm2.plist

# TODO: set the default color scheme in iterm, not sure how to do that automatically
