---

- name: Install neovim
  homebrew:
    name: neovim
    state: present

- name: Configure shell
  template: src="zshrc.j2" dest="~/.zshrc.d/nvim.zsh" mode=0644

- name: Install neovim python2 modules
  pip:
    name: neovim
    executable: pip2

- name: Install neovim python3 modules
  pip:
    name: neovim
    executable: pip3

- name: Prepare Neovim configuration directories
  file: path=~/{{ item }} state=directory
  with_items:
    - .local/share/nvim/site/autoload
    - .vim/plugged
    - .vim/tmp/undo
    - .vim/tmp/backup
    - .vim/tmp/swap
    - .config/nvim

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.local/share/nvim/site/autoload/plug.vim
    mode: 0644

- name: Install Neovim configuration
  copy: src=init.vim dest=~/.config/nvim/init.vim

- name: Update Neovim plugins
  shell: nvim --headless {{ item }}
  with_items:
    - +PlugInstall +qall
    - +UpdateRemotePlugins +qall
