---

- name: Install neovim
  community.general.homebrew:
    name:
      - fd
      - neovim
      - ripgrep

- name: Configure zsh
  ansible.builtin.copy:
    src: zshrc
    dest: "{{ ansible_user_dir }}/.zshrc.d/neovim.zsh"
    mode: '0644'

- name: Prepare neovim configuration directories
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/{{ item }}"
    state: directory
    recurse: true
  with_items:
    - .config/nvim/tmp/undo
    - .config/nvim/tmp/backup
    - .config/nvim/tmp/swap

- name: Install neovim configuration
  ansible.builtin.copy:
    src: config/
    dest: "{{ ansible_user_dir }}/.config/nvim/"
    mode: '0644'
