---

- name: Install neovim
  community.general.pacman:
    name:
      - fd
      - neovim
      - ripgrep
    executable: yay

- name: Configure zsh
  ansible.builtin.copy:
    src: zshrc
    dest: /home/trond/.zshrc.d/neovim.zsh
    mode: '0644'

- name: Install required language servers
  community.general.pacman:
    name:
      - terraform-ls-bin
      - yaml-language-server
    executable: yay

- name: Prepare neovim configuration directories
  ansible.builtin.file:
    path: "/home/trond/{{ item }}"
    state: directory
    recurse: true
  with_items:
    - .config/nvim/tmp/undo
    - .config/nvim/tmp/backup
    - .config/nvim/tmp/swap

- name: Install neovim configuration
  ansible.builtin.copy:
    src: config/
    dest: /home/trond/.config/nvim/
    mode: '0644'
