---

- name: Uninstall regular vim
  community.general.pacman:
    name: vim
    state: removed
  become: true

- name: Install neovim
  community.general.pacman:
    name:
      - neovim
  become: true

- name: Configure zsh
  ansible.builtin.copy:
    src: init.vim
    dest: /home/trond/.config/nvim/init.vim

- name: Prepare neovim configuration directories
  ansible.builtin.file:
    path: "/home/trond/{{ item }}"
    state: directory
    recurse: true
  with_items:
    - .local/share/nvim/site/autoload
    - .config/nvim/plugged
    - .config/nvim/tmp/undo
    - .config/nvim/tmp/backup
    - .config/nvim/tmp/swap

- name: Install vim-plug
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: /home/trond/.local/share/nvim/site/autoload/plug.vim
    mode: '0644'

- name: Install neovim configuration
  ansible.builtin.copy:
    src: init.vim
    dest: /home/trond/.config/nvim/init.vim
    mode: '0644'

- name: Update Neovim plugins
  ansible.builtin.shell: nvim --headless +PlugInstall +qall
