---

- name: Install neovim prerequisites
  ansible.builtin.apt:
    name:
      - fd-find
      - ripgrep
    state: present
  become: true

- name: Install neovim {{ neovim_version }}
  ansible.builtin.apt:
    deb: https://github.com/neovim/neovim/releases/download/v{{ neovim_version }}/nvim-linux64.deb
  become: true

- name: Configure shell
  ansible.builtin.copy:
    src: zshrc
    dest: "{{ ansible_user_dir }}/.zshrc.d/neovim.zsh"
    mode: '0644'

- name: Prepare neovim configuration directories
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/{{ item }}"
    state: directory
    recurse: true
  with_items:
    - .config/nvim/tmp/undo
    - .config/nvim/tmp/backup
    - .config/nvim/tmp/swap

- name: Install neovim configuration
  ansible.builtin.copy:
    src: config/
    dest: "{{ ansible_user_dir }}/.config/nvim/"
    mode: '0644'
