---

- name: Install Ruby
  homebrew:
    name: ruby
    state: present

- name: Configure shell
  template: src="zshrc.j2" dest="~/.zshrc.d/ruby.zsh" mode=0644

- name: Install gems
  gem:
    name: "{{item}}"
    state: latest
    user_install: no
    executable: "/usr/local/opt/ruby/bin/gem" # use the homebrew ruby, might not be in PATH yet
  with_items:
    - rubocop
    - ruby-debug-ide
    - solargraph
    - debase
