---

- name: Install font casks
  homebrew_cask:
    name:
      - homebrew/cask-fonts/font-menlo-for-powerline
      - homebrew/cask-fonts/font-droid-sans-mono-for-powerline
      - font-roboto-mono-for-powerline
      - font-robotomono-nerd-font
      - font-hack-nerd-font
      - font-fira-code
    state: present

- name: Install font files
  copy: src={{item}} dest=~/Library/Fonts/{{item}}
  with_items:
    - "Monaco for Powerline.otf"
    - "SFMono-Bold.otf"
    - "SFMono-BoldItalic.otf"
    - "SFMono-Heavy.otf"
    - "SFMono-HeavyItalic.otf"
    - "SFMono-Light.otf"
    - "SFMono-LightItalic.otf"
    - "SFMono-Medium.otf"
    - "SFMono-MediumItalic.otf"
    - "SFMono-Regular.otf"
    - "SFMono-RegularItalic.otf"
    - "SFMono-Semibold.otf"
    - "SFMono-SemiboldItalic.otf"
